certificate_generator/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from rest_framework import routers
from certificate_app.views import StudentViewSet

router = routers.DefaultRouter()
router.register('students', StudentViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('certificate/', include('certificate_app.urls')),
    path('certificate/verify/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

urlpatterns=[
  path('register/',views.registration, name='register'),
  path('',views.login_user, name='login'),
  path('logout/', views.logout_view, name='logout'),
]

certificate_app/models.py
from django.db import models
from django.utils import timezone


# Model representing different authorities.
class Authority(models.Model):
    auth_id = models.IntegerField(null=True)
    organization = models.CharField(max_length=255, null=True)
    name = models.CharField(max_length=255, null=True)
    designation = models.CharField(max_length=255)
    signature = models.ImageField(upload_to='signatures/')
    
    def __str__(self):
        return self.name


# Model representing different courses.
class Course(models.Model):
    course_name = models.CharField(max_length=100, null=True)

    def __str__(self):
        return self.course_name if self.course_name else ''
    
    class Meta:
        verbose_name ="Courses of Certificates"
        verbose_name_plural = "Courses of Certificates"



# Model representing different types of certificates.
class CertificateTypes(models.Model):
    certify_type_id=models.IntegerField(null=True)
    certificate_type = models.CharField(max_length=100)
    courses = models.ManyToManyField(Course, related_name='certificate_types')
    
    def __str__(self):
        course_list = ', '.join([course.course_name for course in self.courses.all()])
        return f"{self.certificate_type} - Courses: {course_list}"

    def get_certificate(self):
        self.certificate_type

    class Meta:
        verbose_name ="Certificate Types"
        verbose_name_plural = "Certificate Types"



# model for partner that related to tronix
class Partner(models.Model):
    name = models.CharField(max_length=255)
    logo = models.ImageField(upload_to='media/partners/')  # Field to store partner logo images
    width = models.FloatField(default=80)  # Field to store the width of the logo
    height = models.FloatField(default=40)  # Field to store the height of the logo

    def __str__(self):
        return self.name
    
    


# model representing items of tronix
class TronixItems(models.Model):
    items =models.CharField(max_length=255, null=True)

    def __str__(self):
        return self.items
    
    class Meta:
        verbose_name ="Tronix items"
        verbose_name_plural = "Tronix Items"





# model for tronix details
class Tronix(models.Model):
    season = models.CharField(max_length=100, null=True)
    date = models.DateField(default=timezone.now)
    item = models.ForeignKey(TronixItems, on_delete=models.CASCADE, null=True)
    partner_logos = models.ManyToManyField(Partner)  # Field to associate partner logos with each student
    
    def __str__(self):
        return self.season
    
    def get_partners(self):
        """
        Get partners associated with this Tronix season.
        """
        return self.partner_logos.all()

    class Meta:
        verbose_name ="Tronix Certificate "
        verbose_name_plural = "Tronix Certificate"


# model for student of tronix
class StudentTronix(models.Model):
    name= models.CharField(max_length=255, null=True)
    school= models.CharField(max_length=255, null=True)
    issued_date = models.DateField(default=timezone.now)
    place = models.CharField(max_length=255, null=True)
    created_at = models.DateTimeField( default=timezone.now)  # Add this field to store creation time
    certificate_number = models.CharField(max_length=20, null=True, blank=True)  # Changed field name to certificate_number
    tronix_details = models.ForeignKey(Tronix, on_delete=models.CASCADE, null=True)
    certificate_type = models.ForeignKey(CertificateTypes, on_delete=models.CASCADE, null=True)
    position = models.CharField(max_length=255, null=True)

    def save(self, *args, **kwargs):
        # Set issued_date to the current date if it's not already set
        if not self.issued_date:
            self.issued_date = timezone.now().date()
        if not self.pk:  # If the instance is being created (not updated)
            self.created_at = self.issued_date  # Set created_at to issued_date
        super().save(*args, **kwargs)


    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name ="Student Tronix Data"
        verbose_name_plural = "Student Tronix Data"


# model for student of  workshop
class StudentWorkshop(models.Model):
    name = models.CharField(max_length=255, blank=True, default='')
    college_name = models.CharField(max_length=255, blank=True, default='')
    start_date = models.DateField(default=timezone.now)
    end_date = models.DateField(default=timezone.now)
    mentor_name = models.CharField(max_length=255, blank=True, default='')
    issued_date = models.DateField(default=timezone.now)
    certificate_type = models.ForeignKey(CertificateTypes, on_delete=models.CASCADE, related_name='student', null=True)
    course= models.ForeignKey(Course, on_delete=models.CASCADE, related_name='enrolled_student', null=True)
    created_at = models.DateTimeField( default=timezone.now)  # Add this field to store creation time
    certificate_number = models.CharField(max_length=20, null=True, blank=True)  # Changed field name to certificate_number

    def save(self, *args, **kwargs):
        # Set issued_date to the current date if it's not already set
        if not self.issued_date:
            self.issued_date = timezone.now().date()
        if not self.pk:  # If the instance is being created (not updated)
            self.created_at = self.issued_date  # Set created_at to issued_date
        super().save(*args, **kwargs)


    def get_certificatenumber(self):
        if self.certificate_number:
            return True  # Certificate is valid
        else:
            return False  # Certificate is invalid    

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name ="Student Workshop Data"
        verbose_name_plural = "Student Workshop Data"
    

# model for student of internship and workshop
class Student(models.Model):
    name = models.CharField(max_length=255, blank=True, default='')
    college_name = models.CharField(max_length=255, blank=True, default='')
    start_date = models.DateField(default=timezone.now)
    end_date = models.DateField(default=timezone.now)
    mentor_name = models.CharField(max_length=255, blank=True, default='')
    issued_date = models.DateField(default=timezone.now)
    certificate_type = models.ForeignKey(CertificateTypes, on_delete=models.CASCADE, related_name='students', null=True)
    course= models.ForeignKey(Course, on_delete=models.CASCADE, related_name='enrolled_students', null=True)
    created_at = models.DateTimeField( default=timezone.now)  # Add this field to store creation time
    certificate_number = models.CharField(max_length=20, null=True, blank=True)  # Changed field name to certificate_number
    digital_sign = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        # Set issued_date to the current date if it's not already set
        if not self.issued_date:
            self.issued_date = timezone.now().date()
        if not self.pk:  # If the instance is being created (not updated)
            self.created_at = self.issued_date  # Set created_at to issued_date
        super().save(*args, **kwargs)


    def get_certificatenumber(self):
        if self.certificate_number:
            return True  # Certificate is valid
        else:
            return False  # Certificate is invalid    

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name ="Student Internship Data"
        verbose_name_plural = "Student Internship Data"
  

# model for Student of industrial visit(iv)
class StudentIV(models.Model):
    name = models.CharField(max_length=255, blank=True, default='')
    sem_year =models.CharField(max_length=100, blank=True, default='')
    dept =models.CharField(max_length=255, blank=True, null=True, default='')
    college_name = models.CharField(max_length=255, blank=True, default='')
    duration = models.CharField(max_length=255, blank=True, default='')
    mentor_name = models.CharField(max_length=255, blank=True, default='')
    conducted_date = models.DateField(default=timezone.now)
    issued_date = models.DateField(default=timezone.now)
    created_at = models.DateTimeField( default=timezone.now)  # Add this field to store creation time
    certificate_type = models.ForeignKey(CertificateTypes, on_delete=models.CASCADE,  null=True)
    course= models.ForeignKey(Course, on_delete=models.CASCADE, null=True)
    certificate_number = models.CharField(max_length=20, null=True, blank=True)  # Changed field name to certificate_number

    
    def save(self, *args, **kwargs):
        # Set issued_date to the current date if it's not already set
        if not self.issued_date:
            self.issued_date = timezone.now().date()
        if not self.pk:  # If the instance is being created (not updated)
            self.created_at = self.issued_date  # Set created_at to issued_date
        super().save(*args, **kwargs)


    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name ="Student IV Data"
        verbose_name_plural = "Student IV Data"
  

# Model representing the relationship between students and authorities.
class StudentRelatedAuthority(models.Model):
    std = models.ForeignKey(Student, on_delete=models.CASCADE, null=True, blank=True)
    std_workshop = models.ForeignKey(StudentWorkshop, on_delete=models.CASCADE, null=True, blank=True)
    std_iv = models.ForeignKey(StudentIV, on_delete=models.CASCADE, null=True, blank=True)
    std_tronix = models.ForeignKey(StudentTronix, on_delete=models.CASCADE, null=True, blank=True)
    authority = models.ForeignKey(Authority, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return str(self.std)
    

# class StudentRelatedCourse(models.Model):
#     std = models.ForeignKey(Student, on_delete=models.CASCADE)
#     course = models.ForeignKey(Course, on_delete=models.CASCADE)

#     def __str__(self):
#         return self.std
   

templates/certificate_verify_form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Certify</title>
    <link rel="icon" href="/static/images/icon/Certify_logo_icon.png" type="image/x-icon">

    {% load static %}
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/6.5.1/css/font-awesome.min.css">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@500&family=Libre+Baskerville:ital@0;1&family=MonteCarlo&display=swap"
        rel="stylesheet">

</head>

<body class="ceriti-verify-form">
    <div class="container">
        <div class="row">
            <div class="col-md-6 d-flex align-items-center">
                <!-- <img src="{% static 'images/icon/certify_logo.png' %}" alt="Certify Logo" width="215" height="86" class="mt-2"> -->
            </div>
        </div>
        <div class="row">
            
            <div class="col-md-6 text-justify mx-auto">
                <div class="card mt-3">
                    <div class="card-body p-5">
                        <img src="{% static 'images/icon/certify_logo.png' %}" alt="Certify Logo" width="215" height="86" class="mx-auto d-block">

                        <h2 class="text-center mb-5 mt-4">Check Verified Certificate</h2>
                        <form method="post" action="{% url 'certificate_verify' %}">
                            {% csrf_token %}

                            <!-- Include necessary HTML and JavaScript -->
                            <div class="form-group">
                                <b><label for="id_certificate_type" class="mb-2">Certificate Type:</label></b><br>
                                <select id="id_certificate_type" name="certificate_type" class=" form-control">
                                    <option class="verify-select-option">Select Certificate Type</option>
                                    {% for certificate_type in certificate_types %}
                                    <option value="{{ certificate_type.id }}">{{ certificate_type.certificate_type }}
                                    </option>
                                    {% endfor %}
                                </select>
                            </div>
                            <br>

                            <!-- Certificate Type: <input type="text" name="certificate_type"><br> -->
                            <div class="form-group">
                                <b><label for="id_certificate_number: " class="mb-2">Certificate Number: </label></b><br>
                                <input type="text" name="certificate_number" class="form-control">
                            </div><br>
                                <input class="btn btn-primary btn-md btn-block" type="submit" value="Submit">
                            
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

</html>

templates/delete.html
<!-- student_form.html -->
{% extends 'base.html' %}
{% load static %}
{% block body %}
<!-- <div class="animsition">
  <div class="page-wrapper"> -->
    <div class="main-content">
      <div class="section__content section__content--p30">
        <div class="container">
          <div class="row">
            <div class="col-md-6 col-sm-12 mx-auto">
            
              <div class="card text-justify mt-5">
                <div class="card-body form-body p-5">
                  <h5 class="card-title text-center">Student Data delete Form</h5>
                  <p class="card-text">
                  <form method="post" action="" class="frm">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input class="btn btn-primary" type="submit" name="submit_form" value="submit">
                  </form>

                  
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <!-- </div>
</div> -->
{% endblock %}

templates/error_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Error Page</title>
</head>
<body>
    <h1>Invalid Certificate</h1>
    <p>We're sorry, but the certificate you provided could not be verified.</p>
    <!-- You can add more information or instructions here as needed -->
</body>
</html>

templates/student_form.html
<!-- student_form.html -->
{% extends 'base.html' %}
{% load static %}
{% block body %}

<div class="main-content">
  <div class="section__content section__content--p30">
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-sm-12 mx-auto">

          <div class="card text-justify mt-5">
            <div class="card-body form-body p-5">
              <h5 class="card-title text-center">Student Data Form</h5>
              <p class="card-text">

              <form method="post" action="" class="frm">
                {% csrf_token %}
                <label for="id_certificate_number">Certificate Number:</label>
                <input type="text" id="id_certificate_number" name="certificate_number"
                  value="{{ student.certificate_number }}"><br>
                <label for="id_name">Name:</label>
                <input type="text" id="id_name" name="name" value="{{ student.name }}"><br>
                <label for="id_college_name">College Name:</label>
                <input type="text" id="id_college_name" name="college_name" value="{{ student.college_name }}"><br>
                <label for="id_start_date">Start Date:</label>
                <input type="date" id="id_start_date" name="start_date" value="{{ student.start_date }}"><br>
                <label for="id_end_date">End Date:</label>
                <input type="date" id="id_end_date" name="end_date" value="{{ student.end_date }}"><br>
                <label for="id_mentor_name">Mentor Name:</label>
                <input type="text" id="id_mentor_name" name="mentor_name" value="{{ student.mentor_name }}"><br>

                <!-- Include necessary HTML and JavaScript -->
                <label>Certificates:</label><br>
                <select id="id_certificate_type" name="certificate_type">
                  {% for certificate_type in certificate_types %}
                  <option value="{{ certificate_type.id }}">{{ certificate_type.certificate_type }}</option>
                  {% endfor %}
                </select><br>

                <!-- Authorities checkboxes -->
                <label>Authorities:</label><br>
                {% for authority in authorities %}
                <div class="authority-checkbox">
                  <input type="checkbox" id="authority_{{ authority.pk }}" name="authority" value="{{ authority.pk }}">
                  <label for="authority_{{ authority.pk }}">{{ authority.name }}</label>
                </div>
                {% endfor %}
                <div class="mt-3">
                  <label for="my_checkbox">Want Digital Sign:</label>
                  <input type="checkbox" id="my_checkbox" name="my_checkbox" value="yes">
                </div>
                <!-- Courses dropdowns -->
                <!-- {% for certificate_type in certificate_types %}
                <div id="courses_{{ certificate_type.id }}" class="courses">
                  <label>Courses:</label>
                  <select id="courses_{{ certificate_type.id }}" name="courses">
                    {% for course in certificate_type.courses.all %}
                    <option value="{{ course.id }}">{{ course.course_name }}</option>
                    {% endfor %}
                  </select><br>
                </div>
                {% endfor %} -->


                {% for certificate_type in certificate_types %}
                <div id="courses_{{ certificate_type.id }}" class="courses">
                  <label>Courses for {{ certificate_type.certificate_type }}:</label>
                  <select id="courses{{ certificate_type.id }}" name="courses-{{ certificate_type.id }}">
                    {% for course in certificate_type.courses.all %}
                    <option value="{{ course.id }}">{{ course.course_name }}</option>
                    {% endfor %}
                  </select><br>
                </div>
                {% endfor %}


                <input class="btn btn-primary" type="submit" name="submit_form" value="submit">
              </form>


              <p class="text-center p-3">---- Or ----</p>

              <h4 class="mb-4">Upload CSV File</h4>
              <div class="col-md-12">
                <form method="post" enctype="multipart/form-data" class="csv_upload_form">
                  {% csrf_token %}
                  {{ upload_form.as_p }}
                  <input class="btn btn-primary" type="submit" name="upload_csv" value="Upload">
                </form>
              </div>

              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  // Function to show/hide courses based on selected certificate type
  function updateCourses() {
    // Hide all courses dropdowns
    var coursesContainers = document.querySelectorAll('.courses');
    coursesContainers.forEach(function (container) {
      container.style.display = 'none';
    });

    // Get the selected certificate type
    var certificateTypeId = document.getElementById('id_certificate_type').value;
    var selectedCoursesContainer = document.getElementById('courses_' + certificateTypeId);

    // Show courses dropdown for the selected certificate type
    if (selectedCoursesContainer) {
      selectedCoursesContainer.style.display = 'block';
    }
  }

  // Add event listener to the certificate type dropdown
  document.getElementById('id_certificate_type').addEventListener('change', updateCourses);

  // Call updateCourses initially to show courses for the default certificate type
  updateCourses();
</script>

<!-- <div class="main-content">
      <div class="section__content section__content--p30">
        <div class="container">
          <div class="row">
            <div class="col-md-6 col-sm-12 mx-auto">
            
              <div class="card text-justify mt-5">
                <div class="card-body form-body p-5">
                  <h5 class="card-title text-center">Student Data Form</h5>
                  <p class="card-text">
                    
                  <form method="post" action="" class="frm">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input class="btn btn-primary" type="submit" name="submit_form" value="submit">
                  </form>

                  <p class="text-center p-3">----Or---</p>

                  <h4 class="mb-4">Upload CSV File</h4>
                  <div class="col-md-12">
                    <form method="post" enctype="multipart/form-data" class="csv_upload_form">
                      {% csrf_token %}
                      {{ upload_form.as_p }}
                      <input class="btn btn-primary" type="submit" name="upload_csv" value="Upload">
                    </form>
                  </div>
                  
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>  -->

{% endblock %}

templates/student_tronix_form.html
<!-- student_tronix_form.html -->
{% extends 'base.html' %}
{% load static %}
{% block body %}

<div class="main-content">
    <div class="section__content section__content--p30">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-sm-12 mx-auto">

                    <div class="card text-justify mt-5">
                        <div class="card-body form-body p-5">
                            <h5 class="card-title text-center">Student Data Form</h5>
                            <p class="card-text">

                            <form method="post" action="" class="frm">
                                {% csrf_token %}
                                <label for="id_certificate_number">Certificate Number: </label>
                                <input type="text" id="id_certificate_number" name="certificate_number"
                                    value="{{ student.certificate_number }}"><br>

                                <label for="id_name">Name:</label>
                                <input type="text" id="id_name" name="name" value="{{ student.name }}"><br>

                                <label for="id_school">School Name:</label>
                                <input type="text" id="id_school" name="school" value="{{ student.school }}" required>


                                <label for="id_place">Conducted Place:</label>
                                <input type="text" id="id_place" name="place" value="{{ student.place }}"><br>

                                <!-- <label for="id_conducted_date">Conducted Date:</label>
                                <input type="date" id="id_conducted_date" name="conducted_date"
                                    value="{{ student.conducted_date }}"><br> -->

                                <!-- <label for="id_season">Season:</label><br>
                                <select id="id_season" name="season">
                                    {% for tronix in tronix_list %}
                                    <option value="{{ tronix.id }}">{{ tronix.season }}</option>
                                    {% endfor %}
                                </select><br>

                                <label for="id_tronix_item">Tronix Item:</label><br>
                                <select id="id_tronix_item" name="tronix_item">
                                    {% for tronix_item in tronix_item_list %}
                                    <option value="{{ tronix_item.id }}">{{ tronix_item.items }}</option>
                                    {% endfor %}
                                </select><br> -->
                                <!-- <label for="id_season">Season:</label><br>
                                <select id="id_season" name="season">
                                    {% for tronix in tronix_list %}
                                    <option value="{{ tronix.id }}">{{ tronix.season }}</option>
                                    {% endfor %}
                                </select><br>

                                <label for="id_tronix_item">Tronix Item:</label><br>
                                <select id="id_tronix_item" name="tronix_item">
                                    {% for tronix_item in tronix_item_list %}
                                    <option value="{{ tronix_item.id }}">{{ tronix_item.items }}</option>
                                    {% endfor %}
                                </select><br> -->
                                <label for="id_season">Season:</label><br>
                                <select id="id_season" name="season">
                                    {% for tronix in tronix_list %}
                                    <option value="{{ tronix.season }}">{{ tronix.season }}</option>
                                    {% endfor %}
                                </select><br>

                                <label for="id_tronix_date">Conducted Date:</label><br>
                            
                                <!-- <input type="text" id="id_tronix_date" name="tronix_date" value="{{ tronix.date|date:'Y-m-d' }}"><br>
                               -->
                                <select id="id_tronix_date" name="tronix_date">
                                    {% for tronix in tronix_list %}
                                    <option value="{{ tronix.date|date:'Y-m-d' }}">{{ tronix.date|date:'Y-m-d' }}</option>
                                    {% endfor %}
                                </select><br>

                                <label for="id_tronix_item">Tronix Item:</label><br>
                                <select id="id_tronix_item" name="tronix_item">
                                    {% for tronix in tronix_list %}
                                    <option value="{{ tronix.item }}">{{ tronix.item }}</option>
                                    {% endfor %}
                                </select><br>


                                <label for="id_position">Position/Participated:</label>
                                <select name="position" id="position">
                                    <option value="Participated">Participated</option>
                                    <option value="First Position">First Position</option>
                                    <option value="Second Position">Second Position</option>
                                    <option value="Third Position">Third Position</option>
                                </select>

                                <!-- Include necessary HTML and JavaScript -->
                                <label>Certificates:</label><br>
                                <select id="id_certificate_type" name="certificate_type">
                                    {% for certificate_type in certificate_types %}
                                    <option value="{{ certificate_type.id }}">{{ certificate_type.certificate_type }}
                                    </option>
                                    {% endfor %}
                                </select><br>

                                <!-- Authorities checkboxes -->
                                <label>Authorities:</label><br>
                                {% for authority in authorities %}
                                <div class="authority-checkbox">
                                    <input type="checkbox" id="authority_{{ authority.pk }}" name="authority"
                                        value="{{ authority.pk }}">
                                    <label for="authority_{{ authority.pk }}">{{ authority.name }}</label>
                                </div>
                                {% endfor %}

                                <input class="btn btn-primary" type="submit" name="tronix_submit_form"
                                    value="student submit form">
                            </form>


                            <p class="text-center p-3">---- Or ----</p>


                            <h4 class="mb-4">Upload CSV File</h4>
                            <div class="col-md-12">
                                <form method="post" enctype="multipart/form-data" class="csv_upload_form">
                                    {% csrf_token %}
                                    {{ upload_form.as_p }}
                                    <input class="btn btn-primary" type="submit" name="upload_csv" value="Upload">
                                </form>
                            </div>

                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- <script>
    // Function to show/hide courses based on selected certificate type
    function updateCourses() {
        // Hide all courses dropdowns
        var coursesContainers = document.querySelectorAll('.courses');
        coursesContainers.forEach(function (container) {
            container.style.display = 'none';
        });

        // Get the selected certificate type
        var certificateTypeId = document.getElementById('id_certificate_type').value;
        var selectedCoursesContainer = document.getElementById('courses_' + certificateTypeId);

        // Show courses dropdown for the selected certificate type
        if (selectedCoursesContainer) {
            selectedCoursesContainer.style.display = 'block';
        }
    }

    // Add event listener to the certificate type dropdown
    document.getElementById('id_certificate_type').addEventListener('change', updateCourses);

    // Call updateCourses initially to show courses for the default certificate type
    updateCourses();
</script> -->


{% endblock %}